run:
  go: "1.20"
  deadline: 2m
linters:
  enable-all: true
  disable:
    # deprecated
    - varcheck
    - scopelint
    - golint
    - exhaustivestruct
    - deadcode
    - ifshort
    - interfacer
    - nosnakecase
    - structcheck
    - maligned
    # ugly
    - varnamelen
linters-settings:
  misspell:
    locale: US
  gci:
    sections:
      - Standard
      - Default